### PR TITLE
Added reload command. Updated as alias for reset command

### PR DESCRIPTION
**Pull request by udhayacommits**
For fixing #64

### CODE REVIEW

**Comment by udhayacommits** [comment]
@bthayer2365 , Please verify changes.
Note: I am a newbie, so kindly explain if something is completely off.

**Comment by bthayer2365** [comment]
Changes look good! I'll test in the morning as a sanity check, then merge.

**Comment by bthayer2365** [comment]
Tested it and it's all good. Merged!

**Comment by udhayacommits** [comment]
@bthayer2365, Thanks for the merge.

**Pull request merged**
