### PR TITLE
Added level 'intro branching'

### PR DESCRIPTION
**Pull request by parkmichael777**

### CODE REVIEW

**Comment by bthayer2365** [comment]
Hey Michael, thanks for the PR! Everything looks good, just a few updates and I'll be happy to merge.

Can you delete these two lines

```
Hit enter to advance.
```
and
```
Great! You just advanced through the first part of the first set of instructions!
```

The user will already have done that in the first level, so they won't need to do that again.

Also, we also already say "let's start using git!" in the commits challenge too, so can you change that last line to something like "Now that we know how to make a branch, we can start seeing how git operates in the real world!"

**Comment by parkmichael777** [comment]
Hey Ben,

I modified those three things and pushed.

Thanks,
Michael Park

**Comment by bthayer2365** [comment]
Looks good! You're merged!

**Comment by parkmichael777** [comment]
Alright, thank you!

**Pull request merged**
