### PR TITLE
Print challenges in a level

### PR DESCRIPTION
**Pull request by Ishan1742**
Implementation of #10

### CODE REVIEW

**Comment by bthayer2365** [comment]
Hey @Ishan1742 Thanks for the PR, I'll review this within the next day!

**Comment by bthayer2365** [comment]
Hey @Ishan1742 , I ran 

```
C:\Users\benth\Programming\test>git gud challenges
Printing challenges for level: "intro"

commits
branching

C:\Users\benth\Programming\test>git gud challenges intro
Printing challenges for level: "intro"

commits
branching

C:\Users\benth\Programming\test>git gud challenges merging
Printing challenges for level: "merging"

octopus
```
All that looks good.

I ran this:
```
C:\Users\benth\Programming\test>git gud load merging
Setting up challenge: "merging octopus"
Setup complete
Type "git gud instructions" to view instructions

C:\Users\benth\Programming\test>git gud challenges 
Printing challenges for level: "intro"

commits
branching

C:\Users\benth\Programming\test>cat .git\gud\level
intro commits
C:\Users\benth\Programming\test>echo merging octopus > .git\gud\level

C:\Users\benth\Programming\test>git gud challenges
Printing challenges for level: "merging"

octopus
```
This failure is mostly my fault since switching levels doesn't work properly (as of the commit your code is based off of), so I manually set the level and the output was as expected. This part is good.


I ran this
```
C:\Users\benth\Programming\test>git gud challenges mergeing
Traceback (most recent call last):
  File "C:\Users\benth\Miniconda3\envs\git-gud\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\benth\Miniconda3\envs\git-gud\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\users\benth\programming\git-gud\gitgud\__main__.py", line 244, in <module>
    GitGud().parse()
  File "c:\users\benth\programming\git-gud\gitgud\__main__.py", line 237, in parse
    self.command_dict[args.command](args)
  File "c:\users\benth\programming\git-gud\gitgud\__main__.py", line 169, in handle_challenges
    level = all_levels[args.level_name]
KeyError: 'mergeing'
```
This is unexpected input and the command should fail, but when `git gud challenges mergeing` fails, can you check for the KeyError manually and "fail gracefully" by stating "there is no level mergeing" and say that the levels can be viewed by typing `git gud levels`. 

If you want, you can either exit right after that or print out the challenges for the current level. That last part is up to you.

Once all the commands work properly, I'll take a look at the code itself, and from there if all looks good, I can merge it! Thanks for the PR!

**Comment by Ishan1742** [comment]
Ok sure I'll do that.

**Comment by Ishan1742** [comment]
I did add a check for KeyError. But even without that it was working in my computer because I had put it in a try except block. I think it might be a windows issue?? Anyways check the current print challenges and do let me know if any more changes required. Thanks.

Screenshot from 2019-10-12 23-26-58

This was the output before the current commit.

**Comment by bthayer2365** [comment]
Just ran it all. Output looks great. Code looks great.

Two things, then we're good to go:
1. If you wouldn't mind, can you change the flag from being 0/1 to False/True
2. When you get a KeyError, add a print statement that tells the user to run the  "git gud levels" command so if a user wants to figure out which level they're trying to talk about, they can.

**Comment by Ishan1742** [comment]
I guess this should do it.

**Comment by bthayer2365** [comment]
Yep. That does it! Thank you @Ishan1742 . Your changes are merged!

**Comment by Ishan1742** [comment]
Thanks. Happy to contribute. I will continue with the next issue 😀.

**Pull request merged**
