### PR TITLE
Rename level merging to extras

### PR DESCRIPTION
**Pull request by TSSlade**
Blasted from scratch, tried to make all the fixes anew from scratch. I think these cover #46 .

### CODE REVIEW

**Comment by bthayer2365** [comment]
Thanks, just tested this. You'll need to make sure you change the level in `gitgud\levels\__init__.py` too

```
Traceback (most recent call last):
  File "C:\users\benth\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\users\benth\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\users\benth\programming\git-gud\gitgud\__main__.py", line 11, in <module>
    from gitgud.operations import get_operator
  File "c:\users\benth\programming\git-gud\gitgud\operations.py", line 10, in <module>
    from gitgud.levels import all_levels
  File "c:\users\benth\programming\git-gud\gitgud\levels\__init__.py", line 5, in <module>
    from gitgud.levels.merging import all_challenges as merging_challenges
ImportError: cannot import name 'all_challenges'
```

**Comment by TSSlade** [comment]
Just pushed an update. You say no need to PR again, it'll be tracked?

Is there some kind of continuous integration thing going that I could run on my end to make sure everything functions before I push something broken?

**Comment by bthayer2365** [comment]
Unfortunately, we don't have any CI yet, but it's one of the next things on on the to do list. Since the project isn't extremely complicated yet, I can find most of the issues by testing manually and by reading the code. 

In regards to PR commit tracking, the PR references a branch, and all changes to that branch are included in the pull request. Your initial pull requests were all based off of master, so when you kept doing work and opening up new pull requests, they were all referring to the same branch and all had the same changes. Take a look, #56 and #58 have the same changes.

**Comment by bthayer2365** [comment]
This looks good, congrats on your first merge!

**Pull request merged**
